# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1279, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(1280, 720))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(20)
        Form.setFont(font)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(-10, -30, 1431, 751))
        self.frame.setStyleSheet("#frame{background-image: url(:/backimage/Snipaste_2021-12-04_21-15-09.png);\n"
                                 "}\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(210, 80, 421, 71))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(36)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_video = QtWidgets.QLabel(self.frame)
        self.label_video.setGeometry(QtCore.QRect(100, 190, 640, 480))
        self.label_video.setStyleSheet("border-style:outset;               \n"
                                       "                   border-width:10px;                    \n"
                                       "                                 \n"
                                       "                   border-color:rgba(255,255,255,255);    \n"
                                       "\n"
                                       "")
        self.label_video.setText("")
        self.label_video.setObjectName("label_video")
        self.pushButton_Face = QtWidgets.QPushButton(self.frame)
        self.pushButton_Face.setGeometry(QtCore.QRect(800, 350, 421, 101))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_Face.setFont(font)
        self.pushButton_Face.setStyleSheet("\n"
                                           "QPushButton#pushButton_Face{\n"
                                           "    border-radius: 20px;\n"
                                           "    color: white;\n"
                                           "    padding: 16px 32px;\n"
                                           "    text-align: center;\n"
                                           "    text-decoration: none;\n"
                                           "    font-size: 40px;\n"
                                           "    margin: 4px 2px;\n"
                                           "    background-color: white;\n"
                                           "    color: black;\n"
                                           "    border: 2px solid rgba(103,225,255,255);\n"
                                           "}\n"
                                           "QPushButton#pushButton_Face:hover {\n"
                                           "    background-color:rgba(103,225,255,255);\n"
                                           "    color: white;\n"
                                           "}\n"
                                           "QPushButton#pushButton_Face:pressed {\n"
                                           "    background-color: rgba(19,30,95,255);\n"
                                           "}")
        self.pushButton_Face.setObjectName("pushButton_Face")
        self.pushButton_close = QtWidgets.QPushButton(self.frame)
        self.pushButton_close.setGeometry(QtCore.QRect(800, 460, 421, 101))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setStyleSheet("\n"
                                            "QPushButton#pushButton_close{\n"
                                            "    border-radius: 20px;\n"
                                            "    color: white;\n"
                                            "    padding: 16px 32px;\n"
                                            "    text-align: center;\n"
                                            "    text-decoration: none;\n"
                                            "    font-size: 40px;\n"
                                            "    margin: 4px 2px;\n"
                                            "    background-color: white;\n"
                                            "    color: black;\n"
                                            "    border: 2px solid rgba(103,225,255,255);\n"
                                            "}\n"
                                            "QPushButton#pushButton_close:hover {\n"
                                            "    background-color:rgba(103,225,255,255);\n"
                                            "    color: white;\n"
                                            "}\n"
                                            "QPushButton#pushButton_close:pressed {\n"
                                            "    background-color: rgba(19,30,95,255);\n"
                                            "}")
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_exit = QtWidgets.QPushButton(self.frame)
        self.pushButton_exit.setGeometry(QtCore.QRect(800, 570, 421, 101))
        font = QtGui.QFont()
        font.setFamily("SimSun")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setStyleSheet("\n"
                                           "QPushButton#pushButton_exit{\n"
                                           "    border-radius: 20px;\n"
                                           "    color: white;\n"
                                           "    padding: 16px 32px;\n"
                                           "    text-align: center;\n"
                                           "    text-decoration: none;\n"
                                           "    font-size: 40px;\n"
                                           "    margin: 4px 2px;\n"
                                           "    background-color: white;\n"
                                           "    color: black;\n"
                                           "    border: 2px solid rgba(103,225,255,255);\n"
                                           "}\n"
                                           "QPushButton#pushButton_exit:hover {\n"
                                           "    background-color:rgba(103,225,255,255);\n"
                                           "    color: white;\n"
                                           "}\n"
                                           "QPushButton#pushButton_exit:pressed {\n"
                                           "    background-color: rgba(19,30,95,255);\n"
                                           "}")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(800, 50, 421, 111))
        self.lcdNumber.setStyleSheet("border:0px")
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_person = QtWidgets.QLabel(self.frame)
        self.label_person.setGeometry(QtCore.QRect(800, 190, 421, 141))
        self.label_person.setStyleSheet("\n"
                                        "QLabel#label_person{\n"
                                        "    border-radius: 20px;\n"
                                        "    color: white;\n"
                                        "    padding: 16px 32px;\n"
                                        "    text-align: center;\n"
                                        "    text-decoration: none;\n"
                                        "    font-size: 40px;\n"
                                        "    margin: 4px 2px;\n"
                                        "    background-color: rgba(103,225,255,255);;\n"
                                        "    color: black;\n"
                                        "    border: 2px solid rgba(103,225,255,255);\n"
                                        "}\n"
                                        "")
        self.label_person.setObjectName("label_person")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AI_CarProgram"))
        self.label_4.setText(_translate("Form",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">请面向摄像头</span></p></body></html>"))
        self.pushButton_Face.setText(_translate("Form", "人脸开锁：关闭"))
        self.pushButton_close.setText(_translate("Form", "关门"))
        self.pushButton_exit.setText(_translate("Form", "退出"))
        self.label_person.setText(_translate("Form", "请按下按钮执行！"))


import backimage_form_rc
